### ISSUE TITLE
输入换行log报错的问题

### ISSUE THREAD

**Issue by fanly** [pubuim/leanchat-svn-plugin#1]
如题：输入带有换行的log，commit时会报错

**Comment by trigged** [comment]
感谢反馈，我尽快测试下

**Comment by trigged** [comment]
@fanly  能否提供下错误信息，我测试了下是没有问题的

**Comment by fanly** [comment]
![91s _l 4opqmz fimin4](https://cloud.githubusercontent.com/assets/1321825/17996702/0abc319e-6b9d-11e6-8b05-3bac7fc7171e.jpg)
![1i wco nlo n zo 9wiev3](https://cloud.githubusercontent.com/assets/1321825/17996705/0eb97838-6b9d-11e6-978c-39a879dd8cd4.jpg)

**Comment by fanly** [comment]
@trigged 你看看~

**Comment by trigged** [comment]
@fanly 看起来比较奇怪，我需要更多信息诊断下，谢谢
- 麻烦修改下 post-hook 最后的代码，输出下 curl 的错误信息
  `curl -X "POST" "$HOOKS" \
     -H "Content-Type: application/json" \
     -d "$payload" >> /tmp/leanchat.log`
- 同时请提供下你的 Webhook 地址，如果担心隐私可以发给我们的客服（小布）

**Comment by geegku** [comment]
@trigged  在centos7 上面，中文会提交失败，可以添加 `LANG=zh_CN.UTF-8 export LANG`
另外换行，确实会发送失败，还没有找到原因

**Comment by trigged** [comment]
@geegku  感谢反馈，我测试下

**Comment by geegku** [comment]
@trigged  看上去是因为  -d "$payload" 这里有回车，导致 curl 没有执行

**Comment by geegku** [comment]
@trigged  回复好快，是直接用在零信客户端处理的吗?

**Comment by geegku** [comment]
`echo $payload > /tmp/payload.log`

`curl -fsSL -X "POST" "$HOOKS" \
	 -H "Content-Type: application/json;charset=UTF-8" \
	 --data @/tmp/payload.log`
把 curl -d 参数换成从文件里面获取，可以解决svn commit 换行推送成功

**Comment by geegku** [comment]
@trigged  @fanly 
echo $payload > /tmp/payload.log

curl -fsSL -X "POST" "$HOOKS" \ -H "Content-Type: application/json;charset=UTF-8" \ --data @/tmp/payload.log
把 curl -d 参数换成从文件里面获取，可以解决svn commit 换行推送成功

**Comment by geegku** [comment]
@trigged @fanly
echo $payload > /tmp/payload.log

curl -fsSL -X "POST" "$HOOKS" \ -H "Content-Type: application/json;charset=UTF-8" \ --data @/tmp/payload.log
把 curl -d 参数换成从文件里面获取，可以解决svn commit 换行推送失败的问题

**Comment by trigged** [comment]
@geegku  不好意思这几天在搬家，我们今天会发个版本 fix

**Comment by trigged** [comment]
已经修复，如果还有问题可以 reopen 谢谢
